"""empty message

Revision ID: 891d98d37488
Revises: 50281a7818eb
Create Date: 2020-07-06 14:23:15.785008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891d98d37488'
down_revision = '50281a7818eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_link')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
